### ISSUE TITLE
Юр текст внизу страницы

### ISSUE THREAD

**Issue by che** [minsk-hackerspace/hackerspace.by#103]
Для ЕРИП-а:
- [ ]  1)
  Нужно разместить внизу страницы текст:
  Первичная организация “Мастерская инновационно-технического творчества”
  общественного объединения “Белорусское общество изобретателей и рационализаторов”
  220005, г. Минск, ул. Смолячкова 14А комн. 2
  УНП 102386174
  Свидетельство о государственной регистрации № 526 от 03.03.2016 года № 189 администрации советского района г. Минска
- [ ] 2)
  
  Ниже текста - картинка ЕРИП-а и ссылка на сам сайт ЕРИП-а. Образец можно посмотреть на http://bike.org.by/

Спасибо.

**Comment by k2m30** [comment]
@che есть на странице контактов.
Узнай, пожалуйста, что именно и где нужно располагать. Со ссылкой на конкретное постановление, а не правила для интернет-магазинов.

**Comment by che** [comment]
1) На странице Контакты(текст вот как есть про свидетельство и телефоны для связи):
Первичная организация “Мастерская инновационно-технического творчества”
общественного объединения “Белорусское общество изобретателей и рационализаторов”
220005, г. Минск, ул. Смолячкова 14А комн. 2
УНП 102386174
Свидетельство о государственной регистрации № 526 от 03.03.2016 года № 189 администрации советского района г. Минска
Тел.: +375 29 3444323
         +375 29 7793185
         +375 29 3179210

2) Логотип ЕРИП либо в Контакты либо в футоре.

3) Разместить информацию как оплатить членские взносы и как сдлеать пожертвования

4) Разместить информацию что делать человеку если он ошибся и ему необходимо вернуть деньги

**Comment by yahor** [comment]
Пакуль толькі першы пункт можна зрабіць
а тры трэба даапісаць, неабходны дакладны тэксты і малюнак каб девелапер зрабіў задачу правільна.

> 2) Логотип ЕРИП либо в Контакты либо в футоре.

3) Разместить информацию как оплатить членские взносы и как сдлеать пожертвования

4) Разместить информацию что делать человеку если он ошибся и ему необходимо вернуть деньги

**Comment by che** [comment]
Сейчас в процессе всё - поэтому отпишусь и сдлеаю по результату.

**Comment by yahor** [comment]
@che статус?
