### ISSUE TITLE
Страница users

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#117]
Или не users, а hackers, название может быть любое.

Но в общем где-то иметь весь список пользователей (зареганых логинов)
Чтобы можно было видеть логин и айди этого пользователя.

Это ступенька необходимая для развития дальше:

- [ ] - Связать айди и номер членского билета (для платежей по ерип)
- [ ] - Связать айди и NFC карточку для входа
- [ ] - Строить красивые графики посещений/взносов выдавать звания.
- [x] - Сделать профайл с возможностью редактировать и добавить фоточку (как у проекта)

![tak](https://cloud.githubusercontent.com/assets/1046777/19190568/f8c8dfa2-8ca6-11e6-8a26-a3fa03d58e76.png)

**Comment by k2m30** [comment]
может тебе api надо, а не страница?

**Comment by Fl0p** [comment]
Апи возможно тоже. Но в начале просто страница.
Вроде страницы проекты, только про людей. Список. для начала тупо чтобы видеть айди.

Чтобы при платеже по ерип его можно было указывать. 
Чтобы потом когда нить заинтегрировать.

**Comment by k2m30** [comment]
[1, "hudbrog@gmail.com"], 
[3, "gutikoff@gmail.com"], 
[4, "jekhor@gmail.com"], 
[5, "victor@lipski.by"], 
[6, "a.parkalov@gmail.com"], 
[7, "sibvilian@gmail.com"], 
[8, "glebon@gmail.com"], 
[9, "sergei.solovich@gmail.com"], 
[11, "kumeysha.pavel@gmail.com"], 
[12, "azizpm@gmail.com"], 
[13, "kuzaxak.tech@gmail.com"], 
[14, "anatoli@rainforce.org"], 
[15, "arthingeil@gmail.com"], 
[16, "qus@tut.by"], 
[17, "mn3m00@gmail.com"], 
[33, "dmitry.minsky@gmail.com"], 
[35, "nadfilka@gmail.com"], 
[36, "nb8@list.ru"], 
[37, "alexander.kolesen@gmail.com"], 
[38, "roux@yandex.ru"], 
[39, "komzpa@gmail.com"], 
[2, "1m@tut.by"],
[40, "nb8nb8nb8@gmail.com"], 
[41, "alexeynikzzz@gmail.com"], 
[42, "sergejey@gmail.com"], 
[43, "vics@eq.by"], 
[45, "alex_grom@yahoo.com"], 
[46, "serg.flop@gmail.com"], 
[44, "jagor.z@gmail.com"], 
[10, "begemotv2718@gmail.com"], 
[47, "sinicyn.artem@gmail.com"], 
[34, "che.pasha@gmail.com"]

**Comment by Fl0p** [comment]
Воу воу. эта штука поменяется еще 100500 раз 
Все-же страничку лучше.

**Comment by k2m30** [comment]
напиши формат, сделаю тебе json по адресу /json

**Comment by vicseq** [comment]
Надо чтобы номер юзера был выбит на камне. И для определённого живого
человека не менялся. Поговорите с Пашей, он сегодня звонил на тему ID
в базе юзеров для оплаты членских взносов.

**Comment by k2m30** [comment]
ну так он и не меняется
с чего бы?

**Comment by vicseq** [comment]
А база бекапится? А там отвалившиеся люди есть.

**Comment by k2m30** [comment]
нет, база не бэкапится, насколько мне известно
в список пользователей возможно только добавление, изменения - нет. комбинация id - emails навсегда.

**Comment by Fl0p** [comment]
@k2m30 фотмат не JSON А примерно такой:

![tak](https://cloud.githubusercontent.com/assets/1046777/19190568/f8c8dfa2-8ca6-11e6-8a26-a3fa03d58e76.png)


И зря база не бэкапится. Ну хоть бы разок в месяц
Это может отдельным тикетом.

**Comment by vicseq** [comment]
Это хорошо, что не меняется, но бэкапить надо.

**Comment by jekhor** [comment]
Бэкапится, но только на три дня.

**Comment by jekhor** [comment]
а, вру, это ж lvee хостинг
Тогда не знаю.

**Comment by che** [comment]
Бэкап только будет настраиваться - всё подготавливается ещё и со стороны lvee.

А давайте ID пользователя в БД и ID участника - это разные ID всё же сделаем?
Бэкап бэкапом - но мало ли придётся что с ID  сделать или сделают.

**Comment by vicseq** [comment]
2016-10-07 16:23 GMT+03:00 pasha chebotarev <notifications@github.com>:

> А давайте ID пользователя в БД и ID участника - это разные ID всё же
> сделаем?

Естественно, так и надо. Вернее, две колонки, сейчас можно для начала
скопировать, но вести раздельно.

**Comment by k2m30** [comment]
@che @vicseq ээ зачем?

**Comment by vicseq** [comment]
Юзер не равен члену.

**Comment by Fl0p** [comment]
@k2m30 ну мало ли :)
Чтобы можно было делать всякое.
Например один юзер два айдишника. Или два юзера один айдишник три кллюча. Мало ли.
Чтобы потом вдруг не уперется куда-то. Например потерял юзер свой эмэйл совсем. Мы ему новый юзер зарегаем с новым емэйлом. А историю взносов можно будет привязать к старому.

Да и измеряются юзер и член в разных сантиметрах.

**Comment by k2m30** [comment]
@Fl0p ересь какая-то.

> Например один юзер два айдишника.

Один человек, два аккаунта

> Например потерял юзер свой эмэйл совсем. Мы ему новый юзер зарегаем с новым емэйлом. А историю взносов можно будет привязать к старому.

Это и так и так делается руками

Ключи - отдельная таблица. юзер - ключ, отношение один ко многим.

**Comment by Fl0p** [comment]
Так и эти айди (членские билеты) думались отдельной таблицей.
С отношением многие ко многим.

Но уж раз ересь - пусть будет один к одному и в одной таблице.

Но хоть колонку то заведи другую отдельную под это значение.
Вдруг заходим не число использовать, а хэш какой-то или буквенную комбинацию.

**Comment by k2m30** [comment]
не, я не готов.
когда будет понятно, что на той стороне, что за ключи и так далее, тогда и будем проектировать.

**Comment by Fl0p** [comment]
Мне вот все понятно. 

Попробую и тебе донести:

Суть такова:
Юзеру при оплате своего маленького членского взноса нужно указать какой-то идентификатор. По которому можно будет понять что он это он.

Впоследствии по этому айди можно определять кому отключить ключ а кому электричество. 
Еще дальше графики рисовать и прочие красивые крутые штуки. Можно грабить корованы.
Но это потом.

Для начала нужно просто список в котором будет видна эта цифиря.

**Comment by jekhor** [comment]
Плюс на морды лиц друг друга посмотреть, а то уже некоторых не знаю.

07 Окт 2016 г. 18:08 пользователь "Fl0p" <notifications@github.com> написал:

**Comment by Fl0p** [comment]
@jekhor 
Ну морды лиц это тоже круто. Но для этого нужно профайлы делать. 
Хотя по функционалу это те-же проекты, но с небольшими изменениями.

**Comment by vicseq** [comment]
А как же privacy?!

**Comment by k2m30** [comment]
@Fl0p 
залогинился на сайте и плати себе, id будет, не вижу поблемы

рано пока. когда будет понятно, как общаться с ерипом, тогда подумаем, как сделать без лишних сущностей.

вот кстати, как это делает webpay, думаю, что там будет то же самое плюс-минус
![default](https://cloud.githubusercontent.com/assets/3995242/19195832/c337c4cc-8ce5-11e6-87ee-b09f7d328134.jpg)
[Персональный кабинет WEBPAY 1.0.2.pdf](https://github.com/minsk-hackerspace/hsWEB/files/516524/WEBPAY.1.0.2.pdf)
[Правила возврата денежных средств.pdf](https://github.com/minsk-hackerspace/hsWEB/files/516521/default.pdf)
[ТРЕБОВАНИЯ К ИНТЕРНЕТ-МАГАЗИНАМ.docx](https://github.com/minsk-hackerspace/hsWEB/files/516523/-.docx)
[WebPay Developer Guide 2.0.0.pdf](https://github.com/minsk-hackerspace/hsWEB/files/516525/WebPay.Developer.Guide.2.0.0.pdf)
[Создание счета 1.0.pdf](https://github.com/minsk-hackerspace/hsWEB/files/516522/1.0.pdf)

**Comment by Fl0p** [comment]
@k2m30 
А если залогинился не на сайте, а в интернет банкинге или вообще стоишь у терминала?

Более того хочется же не только заплатить, но и видеть активность людскую.

Ой всё!
Придется разбиратся в этих ваших рубевых деплоях..
Гитовый публичный ключик подойдет или новый генерить?

**Comment by k2m30** [comment]
у тебя, что, винда?

**Comment by Fl0p** [comment]
макось

**Comment by k2m30** [comment]
ну тогда не надо тебе ничего

```bash
brew install ruby
gem install rails --no-ri --no-rdoc
git clone https://github.com/minsk-hackerspace/hsWEB
cd hsWEB
bundle
rails db:setup
rails server
```

и потом на http://localhost:3000 будет твой сервер

**Comment by Fl0p** [comment]
и потом чтобы задеплоить нужен ссх ключик же

**Comment by k2m30** [comment]
ты сделаешь pull-request, мы его смерджим и зальем.
твой ssh ключ из `~/.ssh/id_rsa.pub` я добавлю на сервер, чтобы он тебя пустил.

но вообще, как только в мастер попали изменения, задеплоить может кто угодно.

**Comment by jekhor** [comment]
Пулл-реквест же.

07 Окт 2016 г. 18:55 пользователь "Fl0p" <notifications@github.com> написал:

**Comment by yahor** [comment]
завяршаю "Сделать профайл с возможностью редактировать и добавить фоточку (как у проекта)" 
і хутка зраблю ПР

**Comment by Fl0p** [comment]
@yahor 👍

**Comment by yahor** [comment]
@Fl0p  ёсць карцінкі іконак на экшаны?

**Comment by Fl0p** [comment]
Иконок навалом:

![settings-1](https://cloud.githubusercontent.com/assets/1046777/19625982/add9b4cc-992f-11e6-85c6-0b475f5e66bc.png)
![settings](https://cloud.githubusercontent.com/assets/1046777/19625978/add5d334-992f-11e6-8342-52be86b717a7.png)
![info squared-1](https://cloud.githubusercontent.com/assets/1046777/19625979/add79444-992f-11e6-9d36-06048c1319f3.png)
![info squared](https://cloud.githubusercontent.com/assets/1046777/19625981/add88930-992f-11e6-89fb-388f97b266ab.png)
![info-1](https://cloud.githubusercontent.com/assets/1046777/19625980/add7fab0-992f-11e6-8288-fc1d8e9a8312.png)
![info](https://cloud.githubusercontent.com/assets/1046777/19625983/addb9d5a-992f-11e6-9b77-1f46d0c1f68f.png)


Какие нужны?
Могу тут еще найти например тут - https://icons8.com

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/pull/125 

Мінімальны функцыянал гатовы, засталося разабрацца з статусам.
Як сістэма будзе надаваць статусы юзерам?

**Comment by Fl0p** [comment]
Это предстоит придумать.
Приглашаем к обсуждениию...

**Comment by vicseq** [comment]
Калі можна бета-тэставаць?

**Comment by yahor** [comment]
@vicseq праз 30 хв выкачу код

**Comment by yahor** [comment]
гатова
@vicseq  https://hackerspace.by/hackers 
@Fl0p трэба рэвью і дапрацоўка неабходнага функцыянала ў наступнай ітэрацыі

**Comment by Fl0p** [comment]
Так все же отлично.
Весь базовый функционал который нужен был - есть.
Можно увидеть себя и свой айди.

Нюансы:
Нужна бы хоть какая-то дефолтная картинка, без нее все разъезжается.

![screen shot 2016-10-26 at 11 43 49](https://cloud.githubusercontent.com/assets/1046777/19721711/2923e32a-9b7c-11e6-8e37-e8693e6ea00c.png)

Возьми эту например:
![sq](https://cloud.githubusercontent.com/assets/1046777/19721832/ac8a56e0-9b7c-11e6-962e-1ff91adbbc9a.png)

И коль у нас уже есть дата, то почему бы не сортировать по ней. 
Тогда список будет более удобным.

Еще:
Сам профиль выглядит ну уж очень пустым:
![screen shot 2016-10-26 at 13 06 02](https://cloud.githubusercontent.com/assets/1046777/19721921/03d6a584-9b7d-11e6-8d4d-141671cfe780.png)

Туда бы по хорошему всю инфу что можно разузнать
- Все что уже имеется в этом листе hackers.
- С большой фоткой 
- рендером .md который юзер сам может заполнить (контакты например)
- ссылки на проекты в которых учавствует (которые создал)
- мб что-то еще.

Но это все отдельными тикетами.
А этот можно закрывать.

**Comment by vicseq** [comment]
Увайсці атрымалася. :-)

**Comment by yahor** [comment]
@Fl0p зроблена па апошнім спісе + карцінка
