### ISSUE TITLE
Переименовать репозиторий

### ISSUE THREAD

**Issue by k2m30** [minsk-hackerspace/hackerspace.by#118]
Все никак не доходили руки.
Меня бесит `hsWEB` в списке директорий. Ни два ни полтора. Ни camel case, ни underscore, ни даже -.

Чего его вообще переименовывали?
Предлагаю `hackerspace` или `hackerspace.by`

Если нет идей получше, я сделаю, readme и проект на сайте обновлю.

**Comment by Fl0p** [comment]
А как-же сокровенное: Работает - НЕ ТРОГАЙ

**Comment by jekhor** [comment]
Это ты Толику скажи, который переименовал.

07 Окт 2016 г. 20:08 пользователь "Fl0p" <notifications@github.com> написал:

**Comment by che** [comment]
2016-10-07 19:09 GMT+03:00 Mikhail Chuprysnki <notifications@github.com>:

> Все никак не доходили руки.
> Меня бесит hsWEB в списке директорий. Ни два ни полтора. Ни camel case,
> ни underscore, ни даже -.
>
+100

Да просто: hs-site



-- 
with best regards,
pavel chebotarev.

e-mail: info@chepava.by
mob. tel.: +375 29 3179210

minsk, belarus
http://chepava.by

**Comment by abitrolly** [comment]
Переименован, потому что были всякие попытки уже. Две. Это третья. `hackerspace.by` норм.

**Comment by abitrolly** [comment]
Done.

**Comment by abitrolly** [comment]
@k2m30 так переименовал. что тебе не нравиться опять?

**Comment by k2m30** [comment]
с ревертом твоего коммита, все опять уехало. я исправлю и переименую.

**Comment by abitrolly** [comment]
@k2m30 так а нахера ты его ревертил? Написать нельзя?

**Comment by vicseq** [comment]
����� ��, ���-������������, ��������������!..

**Comment by k2m30** [comment]
обновил, проект на сайте поправил.
