### ISSUE TITLE
Описать тест deploy для тех, у кого нет ключей

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hackerspace.by#119]
По мотивам #111 и #113 - нет инструкций, как тестить деплой, кроме как залить на боевой сервер.

**Comment by che** [comment]
Толя, это всё в настройках travis делается.
Просто добавить конфиг и протисать нак travis-е.

**Comment by che** [comment]
Поменять  IP-шник на 127.0.0.1 и сделать деплой локально. ЧТо ного и удивительного?

**Comment by abitrolly** [comment]
Где менять?

**Comment by che** [comment]
Логично и очевидно, что в конфиге mina. :-)

**Comment by k2m30** [comment]
@che не сработает, ты по ssh к себе не подконнектишься без извращений. 
надо делать отдельный staging и все там разворачивать с нуля.

**Comment by che** [comment]
Миш, всё в отдельном хоме - тогда и сработает. Не делать же в своём лично хоме таккое?!

**Comment by abitrolly** [comment]
Как насчёт документацию из wiki запихать в `doc/`? Мне удобнее локальным поиском эти команды находить, а не в браузер лазить. С точки зрения веб доступа тоже мало чего поменяется - GitHub норм markdown рендерит и позволяет редактировать через браузер.
