### ISSUE TITLE
Предлагаю снести новости

### ISSUE THREAD

**Issue by k2m30** [minsk-hackerspace/hackerspace.by#121]
как предсказуемо неиспользуемую функциональность. Последний апдейт был в феврале.

Вместо него сделать раздел о пользователях. С профилями, фотками и ссылками.

Вернется Наташа, раскоментим.
- [ ]    Неабходна сабраць у спіс задач

**Comment by k2m30** [comment]
#117

**Comment by jekhor** [comment]
Присоединяюсь. Просто убрать ссылку в шапке.

**Comment by k2m30** [comment]
Надо только как-то оставить #63

**Comment by jekhor** [comment]
Сделать какое-нибудь меню выпадающее для зареганых пользователей.

**Comment by jekhor** [comment]
Ну или по принципу "кто знает — зайдёт по прямому урлу", но нехорошо это.

**Comment by k2m30** [comment]
В личном кабинете кнопку

**Comment by Fl0p** [comment]
В личном кабинете кнопку +1
Убрать из главного меню +1
Добавить в главное меню пользователей +1

**Comment by Fl0p** [comment]
И вот еще оставить функцию показывать новость на главной до...

**Comment by yahor** [comment]
@k2m30 прапаную кабінет юзера даапісаць, з выдаленнем калонкі навінаў з пабліка зразумела.

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/pull/129 

пакуль проста прыбраў лінку з галоўнага меню і дадаў меню для хакераў
