### ISSUE TITLE
перенести кнопку [добавить новость]

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#123]
Сейчас кнопка находится где-то в самом конце длинной ленты новостей.
Нужно ее перенести вверх на главное меню и сделать привлекательной для нажимания.

**Comment by k2m30** [comment]
мы же вроде удалять все собрались

**Comment by Fl0p** [comment]
Либо сделать новости рабочими, либо вообще убрать.

Показывать новость на главной до - это вполне годный функционал и его удалять не нужно. 
Просто кнопку ведущей к этой функции нужно сделать видимой!

А вот сам архив протухлых новостей в верхнем меню не нужнен да.

**Comment by k2m30** [comment]
может посты из фб и g+ в качестве новостей?

**Comment by Fl0p** [comment]
Ну можно попробовать.

Но объявка висящая на главной до определенной даты - это годная вещь. Не стоит ее выпиливать. Может назвать ее подругому.

**Comment by yahor** [comment]
калі трэба пераадкрыем
