### ISSUE TITLE
Поменять телеграм линк в контактах

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#126]
В связи с переводом в группы в супергруппу поменялся инвайт линк.
Старый больше не работает. Новый вот:
https://telegram.me/joinchat/Bxa3CT7ai59igvC1dP95Aw
Необходимо поменять линк на странице контакты https://hackerspace.by/contacts

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/pull/127 гатова

**Comment by abitrolly** [comment]
А нельзя его посимпатишнее сделать?

**Comment by yahor** [comment]
@abitrolly па-канкрэтней, лінку на сайце ці сам чат?

**Comment by abitrolly** [comment]
Линка ж была нормальная c именем места, а сейчас непонятный хэш.

**Comment by k2m30** [comment]
Нет, Толик. По-другому нельзя.
Это ограничения телеграма. И раньше тоже было так.

**Comment by Komzpa** [comment]
да ладно, у нас вот https://telegram.me/bygis - и нормально, живём.

**Comment by k2m30** [comment]
Я рад за вас, но для нас ответ тот же.

**Comment by jekhor** [comment]
On Sun, Oct 30, 2016 at 10:02:33AM -0700, Mikhail Chuprysnki wrote:
> Я рад за вас, но для нас ответ тот же.

А в чём разница?

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/minsk-hackerspace/hackerspace.by/issues/126#issuecomment-257163529

-- 
Yauhen Kharuzhy

**Comment by abitrolly** [comment]
> А в чём разница?

Миша намекает, что он тут царь и поэтому имеет право говорить за всю сеть. =)

**Comment by Fl0p** [comment]
> А нельзя его посимпатишнее сделать?
@abitrolly 
Можно, если сделать паблик чат. И тогда можно сделать паблик алиас. Который можно постить везде и повсюду и он будет всегда работать.
А у нас чатик пока приват. И этот непонятный хэш это инвайт линк, который можно отозвать если вдруг надоест. 

Пока люди находят линк и нет необходимости рекламировать его красивый повсюду и зазывать новых людей, я думаю что вполне сгодится такой.

**Comment by k2m30** [comment]
@jekhor Да, разница в степени приватности группы. И да, у нас всегда был хеш.

У меня нет мнения, стоит ли делать группу публичной. Я не знаком с разницей в методах модерации, защиты от спама и так далее.

И я не вижу разницы в виде ссылки до тех пор, пока пользователю не надо вводить ее руками. Кликнуть по ссылке с надписью "Канал в Telegram" одинаково приятно вне зависимости, куда именно она ведет.

Толику, как обычно, надо потрепаться ради потрепаться.

**Comment by k2m30** [comment]
@yahor дзякуй, дарэчы :)
