### ISSUE TITLE
Ccылка на Telegram на главной странице заэкспайрилась

### ISSUE THREAD

**Issue by Komzpa** [minsk-hackerspace/hackerspace.by#131]

**Comment by yahor** [comment]
патрэбна новая спасылка? І часта на яе мяняць? 

Прапаную дадаць у адмінку візівіг ці канфіг для такіх рэчаў і праз адмінку правіць.

**Comment by jekhor** [comment]
Сделать открытую группу и не дурить голову.

**Comment by vicseq** [comment]
И логи канала на сайт!

**Comment by yahor** [comment]
І які вердыкт?

**Comment by vicseq** [comment]
On Fri, Dec 23, 2016 at 5:21 PM, Yahor <notifications@github.com> wrote:

> І які вердыкт?

Всем пох. ;-)

**Comment by Fl0p** [comment]
Убрать ее да и всего делов.

**Comment by k2m30** [comment]
#132 ?
Не оно?
