### ISSUE TITLE
Обновить главную страницу.

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#134]
Главная страница безнадежно устарела.
Необходимо обновить все и текст и фотки.

**Comment by vicseq** [comment]
On Wed, Feb 1, 2017 at 4:07 PM, Fl0p <notifications@github.com> wrote:

> Главная страница безнадежно устарела.
> Необходимо обновить все и текст и фотки.

Насколько я понимаю аморфную политику партии - к такому багу надо
прилагать "и текст, и фотки". Или никто ничего не обновит...

**Comment by Fl0p** [comment]
Чтобы закрыть багу - надо прилагать.
А пока просто issue и тудулист:

- [ ]  фотки
- [ ]  текст

**Comment by k2m30** [comment]
а чем текст некатуален?
фотки можно из звездных статей Олега и Володи набрать

**Comment by vicseq** [comment]
2017-02-02 7:36 GMT+03:00 Mikhail Chuprysnki <notifications@github.com>:

> фотки можно из звездных статей Олега и Володи набрать

Если успешные журналистые не засудют.

**Comment by Fl0p** [comment]
@k2m30 
> а чем текст некатуален?

На мой взгляд есть много вещей которые нуждаются в корректировке. По абзацам:
- Что это такое?  - вроде ок.
- Чем мы здесь занимаемся? - Операции "паяем" "программируем" задвинуть в конец. В начале нужны сами цели для которых совершаются эти операции. А еще неплохо бы добавить ключей для поисковика. Вроде "как сделать minecraft светильник с управлением по хлопку на Arduino"
- Как к нам присоединиться? - вообще все переписать, избавится от $. написать однозначно.
- Что у нас есть? - нужно бы добавить всякое новое. И добавить примеры того что с помощью этого можно делать.
- Как нас найти? - Перефразировать, сейчас звучит как "не приходите" нужно написать в стиле "приходите" и поставить вторым пунктом.

Всегда в тексте написано "мы" "у нас". Но без определения кто такие "мы". Нужны фоточки, небольшое описание, чтобы человек заранее заочно познакомился. Поставить третим пунктом.

**Comment by yahor** [comment]
@Fl0p @k2m30 
трэба гатовыя тэксты, тады калі яны ок, мы іх заменім.
+ якія фоты куды ?

**Comment by yahor** [comment]
ping @Fl0p @k2m30

**Comment by k2m30** [comment]
@yahor меня всё устраивает, не знаю

**Comment by Fl0p** [comment]
@yahor Я запдейчу позже, описал же как. 
Нужно фоточке следенькие наделать (на выходных сделаю)
и с взносами определится (уже сегодня будет).

**Comment by k2m30** [comment]
> (уже сегодня будет) 
ну-ну :)

**Comment by k2m30** [comment]
#304
