### ISSUE TITLE
Сортировка юзеров наоборот.

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#136]
Сейчас сортировка видимо по последней активности что-ли.
Хотелось бы видеть активных вверху страницы. А тех кто не заходит в низу.

![screen shot 2017-02-14 at 19 01 44](https://cloud.githubusercontent.com/assets/1046777/22937020/51fbd5f0-f2e8-11e6-9029-4cff5f313d1a.png)

**Comment by yahor** [comment]
done
