### ISSUE TITLE
Номер членского билета.

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#137]
Сейчас айди юзера виден только на этой странице:

https://hackerspace.by/hackers

Его нужно бы сообщить юзеру на его странице
https://hackerspace.by/hackers/%id% и тут https://hackerspace.by/cabinet

Добавить строку Номер членского билета: %id%

В идеале бы нужно эти две страницы объединить, с соответствующими ограничениями, чтобы видеть и править личную инфу мог только про себя.

**Comment by yahor** [comment]
@jekhor  Ёсць што дадаць сюды?

**Comment by vicseq** [comment]
Так, я б таксама аб'яднаў https://hackerspace.by/hackers/%id% и тут https://hackerspace.by/cabinet і выдаліў магчымасць бачыць асабістае іншых карыстальнікаў.

**Comment by Fl0p** [comment]
О юзере еще можно добавить следущее:
Никнэйм - для отображения в шапке присутствия (пока это делается на Бобе)
И список маков - тоже чтобы не хранить их на Бобе и можно было редактировать прямо на сайте.

**Comment by vicseq** [comment]
2017-02-20 13:54 GMT+03:00 Fl0p <notifications@github.com>:
>
> О юзере еще можно добавить следущее:
> Никнэйм - для отображения в шапке присутствия (пока это делается на Бобе)
> И список маков - тоже чтобы не хранить их на Бобе и можно было редактировать прямо на сайте.

Пожалуй, да, чтобы каждый мог сам свой мак добавить или удалить и
указать, как он будет виден в общедоступном месте.

**Comment by yahor** [comment]
by Vics:

1. https://github.com/minsk-hackerspace/hackerspace.by/issues/140 -
выгрузка ўсёй базы карыстальникаў у звычайным CSV (падзяляльнік коска
- , - радкі ў двукоссях - "" - і г. д.) каб by default зацягвалася ў
libreoffice і sheets.google.com.
2. https://github.com/minsk-hackerspace/hackerspace.by/issues/130 -
згодна з патрабаваннямі bepaid
https://docs.bepaid.by/en/erip/create-payment дадаць у базу
ўдзельнікаў наступныя палі:

first_name имя покупателя. Максимальная длина: 30 символов
middle_name отчество покупателя. Максимальная длина: 30 символов
last_name фамилия покупателя. Максимальная длина: 30 символов
country страна покупателя в ISO 3166-1 alpha-2 формате
city город покупателя. Максимальная длина: 60 символов
zip почтовый индекс покупателя. Максимальная длина: 20 символов
address адрес для выставления счёта. Максимальная длина: 250
phone номер телефона покупателя. Максимальная длина: 30
is_member - boolean - з'яўляецца сябрам ПО МИТТ ОО БОИР. фактычна ўсе
папярэднія палі патрэбныя толькі для тых, хто true.

на старонцы https://hackerspace.by/admin/users для адмінаў дадаць
магчымасць праглядаць і рэдагаваць гэтыя палі для ўсіх у дадатак да
наяўных зараз, кожнаму дазволіць змяняць гэтую інфармацыю для сябе,
больш нікому нідзе гэтую інфармацыю не паказваць;

3. на старонцы https://hackerspace.by/admin/users для адмінаў дадаць
магчымасць выгрузіць на бягучы месяц інфармацыю згодна з
патрабаваннямі bepaid
https://docs.bepaid.by/ru/erip/intro#file-create-erip-payment у
фармаце CSV з падзяляльнікамі pipe ("|") і г. д. у адпаведнасці з
гэтым дакументам. Толькі для тых, хто is_member = true.

4. Калі рэалізаваць стварэнне поручений праз bepaid API параўнальна па
працы з выгрузкай СSV у пункце 3, то не трэба 3, давай адразу 4. Калі
3 значна прасцей, то давай хутка 3, а потым як небудзь 4.

**Comment by che** [comment]
@yahor для API там ещё обработка статусов и креды дополнительные
Если через rake планируется делать работу с API, то это лучше вариант, потомучто можно будет ручками запустить. Совсем всё в движок работу с API - IMHO не вариант.
Дело ещё в том, что не только нужно будет добавить поля которые для запроса формирования нужно - нужно ещё будет поля после получения ответа не только о создании в bePaid, но и после обработки и оплаты.
Ещё к существующим полям ещё поля: order_id, account_number, tracking_id.

**Comment by jekhor** [comment]
Создание счетов при изменении/создании пользователей реализована в PR #175
