### ISSUE TITLE
В репозитории отсутсвует database.yml

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#142]
Не запустить 
```
bundle exec rake db:setup
bundle exec rails server
```

```
.rvm/gems/ruby-2.3.3/gems/railties-5.0.0.1/lib/rails/application/configuration.rb:143:in `database_configuration': Cannot load `Rails.application.database_configuration`: (RuntimeError)
Could not load database configuration. No such file - ["config/database.yml"]
```

Его внесли в гитигнор.
https://github.com/minsk-hackerspace/hackerspace.by/blob/b5c51dc3af9ccf52a6259fc20c124c4267f73ef9/.gitignore#L13

**Comment by k2m30** [comment]
Ты разобрался? Так и должно быть.

**Comment by Fl0p** [comment]
Ну да.

Может можно сделать что-то в том db:setup чтобы генерило конфиг?
В общем хз как правильно, из меня рубист...

В любом случае в доке надо бы записать, а то та how to что есть не запускается сразу из-за таких нюансов.

**Comment by jekhor** [comment]
README поправить надо.

Раньше просто лежал конфиг, сейчас выпилили, надо пример конфига
скопировать для запуска. А, и в пример конфига я бы sqlite для
разработческой базы использовал.

26 Мар 2017 г. 16:04 пользователь "Fl0p" <notifications@github.com> написал:
