### ISSUE TITLE
Рега и восстановление пароля.

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#143]
Сейчас реги нет, Но есть куча юзеров 47-54 которые имеют акк, но не имеют доступа к сайту.
Неплохо бы ри создании юзера (как он там создается) сразу отправить ему пасс.
А так-же запилить возможность вспомнить пароль.

**Comment by vicseq** [comment]
Возможно даже всем сразу сбросить пароли и прислать на e-mail из базы каждому сообщение о восстановлении пароля, когда оно заработает, чтобы члены знали, что account таки существует.

**Comment by k2m30** [comment]
Это не баг, а фича. Так было надо когда-то. Регистрация просто закомметирована в коде. Пользователи создаются руками и руками же высылаются пароли, когда кому-то действительно надо.

**Comment by Fl0p** [comment]
Все еще надо?
Может пора вернуть?

**Comment by k2m30** [comment]
Причины было две – борьба со спамом (мусорными регистрациями) и дополнительный контроль за появлением новых участников. Как показывает последний опыт, это имеет смысл.
Добавить раз в месяц нового человека труда не составляет.

**Comment by k2m30** [comment]
Я готов это делать, если что.

**Comment by Fl0p** [comment]
Ну раз будешь делать - ОК.
Главное не забыть им пароли отдать. 
Я думаю есть у нас еще несколько юзеров без паролей.

**Comment by Fl0p** [comment]
@k2m30 кстати там есть несколько новых которым ключ в ХС дал а регу не дал.
Это норм?

**Comment by k2m30** [comment]
@Fl0p как только они захотят платить через ерип, они придут за паролем.

**Comment by Olgerd96** [comment]
может сразу в инструкцию внести, что если не знаешь свой айди - плати на 0ой или регистрируйся?

**Comment by k2m30** [comment]
есть же

> Если не знаете реквизитов входа на МХС.Бел - напишите на info@hackerspace.by.

https://hackerspace.by/news/15
