### ISSUE TITLE
Дадаць інфармацыю пра ЕРИП да https://hackerspace.by/contacts 

### ISSUE THREAD

**Issue by vicseq** [minsk-hackerspace/hackerspace.by#145]
На https://hackerspace.by/contacts дадаць інфармацыю, як плаціць унёскі з дакументу
https://docs.google.com/document/d/1giiyqS0qYxzfWEjtITAN39inTkbR_F86SjCu-Bn60ys/edit?usp=sharing

**Comment by k2m30** [comment]
Мне кажется, это надо показывать только залогиненым пользоватлям, не надо на сайт пихать всё подряд

**Comment by Fl0p** [comment]
У залогиненых пользователей вообще нужно кнопку [уплотить].
А вот инфа нужна вероятно для того чтобы удовлетворить "требования к сайту" чтобы его указали в самом ЁРИПе

**Comment by vicseq** [comment]
2017-03-30 12:41 GMT+03:00 Mikhail Chuprysnki <notifications@github.com>:
>
> Мне кажется, это надо показывать только залогиненым пользоватлям, не надо на сайт пихать всё подряд

Требования ёрипа. Это как реквизиты внизу
https://hackerspace.by/contacts - дань нечистой силе.

**Comment by k2m30** [comment]
Вот, в новости можно пихать всё, точно. Там один хрен всё потеряется. 
Это лучше, чем на основные страницы.

**Comment by vicseq** [comment]
Куда класть и насколько необходимо - знают @che и @jekhor.

**Comment by jekhor** [comment]
Не решено же, действительно нужно.

**Comment by k2m30** [comment]
есть же.

**Comment by jekhor** [comment]
ОК, переформулирую: "Разместить информацию о том, как платить, в легко находимом очевидном месте"

**Comment by k2m30** [comment]
#184
