### ISSUE TITLE
Контроль физического доступа в ХС по картам

### ISSUE THREAD

**Issue by k2m30** [minsk-hackerspace/hackerspace.by#160]
Тема не новая. Но на сегодня есть следующее:

Считыватель опрашивается n раз в секунду, если приложена NFC карта, то на Raspberry приходит уникальный набор байт - plain ruby код. 
Этот набор нужно сравнить со списком людей, которым разрешен доступ и принять решение открыть дверь или нет.

Что нужно конкретно:
- Механизм приема оплат от ерипа и продление доступа для человека (хакероустройчивый)
- Автономность - при пропадании интернета все по-прежнему должно работать. Т.е. некий push данных (синхронизация таблицы базы) с нашего сайта в систему доступа при прохождении новой оплаты.
- Отказоустойчивость всего этого добра.

Есть софтовый и хардварный объем работы. Джойн.

Пока мы с Флопом пилим тихонько, но работы там хватает.

@jekhor @yahor @che @Fl0p @abitrolly @agutikov

**Comment by Fl0p** [comment]
Проект вот тутака

https://github.com/minsk-hackerspace/Bramnik

**Comment by Fl0p** [comment]
@k2m30 
Что-то я плохо себе представляю как можно сделать хакероустойчивым механизм который представляет из себя малинку с руби кодом к которой есть физический доступ.

**Comment by abitrolly** [comment]
Хакеры учат хаскель и раст, так что всё норм. :)

**Comment by k2m30** [comment]
@abitrolly Толик, у тебя есть прекрасная возможность реализовать сабж на любом языке и технологии, чтобы потом не говорить, что руби плох ;)

**Comment by k2m30** [comment]
stale
