### ISSUE TITLE
Используются Postgresql-специфичные типы данных, разработка на SQLite невозможна

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#162]
В db/migrate/20170325164818_create_erip_transactions.rb:
      t.json :billing_address
      t.json :customer
      t.json :payment
      t.json :erip

Надо или таки вернуться к использованию PG для разработки (что не хочется, SQLIte удобно и быстро разворачивается), либо убрать постгресизмы.

**Comment by che** [comment]
Такое уже не только в PostgreSQL. :-)
Можно конечно JSON хранить в БД в виде строки и каждый раз при обращении парсить и т.д. и т.п.
Но SQLite локально хороша.

**Comment by k2m30** [comment]
@yahor ?

**Comment by jekhor** [comment]
Видимо, надо смириться и закрыть issue.
