### ISSUE TITLE
Автоматические тесты сайта на Travis CI

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hackerspace.by#169]
* https://travis-ci.org/minsk-hackerspace/hackerspace.by

**Comment by jekhor** [comment]
Автотесты бы не помешали, если честно...

**Comment by k2m30** [comment]
Возьмешься? Переоткроем тогда.

**Comment by jekhor** [comment]
Пока нет.

**Comment by abitrolly** [comment]
CI настроен, то что сайт не поднимается уже не моя проблема.

**Comment by k2m30** [comment]
То, что у тебя руки кривые и документацию ты не читаешь - это как раз твоя проблема.

**Comment by abitrolly** [comment]
@k2m30 с личными наездами в другое место, пожалуйста.

**Comment by k2m30** [comment]
Веди себя по-человечески и делай нормально, тогда и общение другое будет.

**Comment by jekhor** [comment]
Closed by 0c03bea315ca39d3d07d706fa632a6cac8d6128e
Исходный .travis.yml был неправильным и непригодным к эксплуатации.
