### ISSUE TITLE
Добавить формализованный механизм принятия решений (голосования/обсуждения)

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#171]
Время от времени возникают вопросы, требующие коллективного принятия решений. Поскольку в рассылке обсуждения обычно затухают и заканчиваются ничем, нужен формализованный автоматизированный механизм.
Возможно, это должно быть голосование с рассылкой уведомлений участникам ХС, возможностью обсуждения и дедлайнами.

**Comment by Fl0p** [comment]
Йопту любую голосовалку заюзать и всего делов.

**Comment by Fl0p** [comment]
Или же можно свою на сайт написать. на рубях. :)

**Comment by Fl0p** [comment]
@k2m30 Выгнать ли дронекса например

**Comment by k2m30** [comment]
@Fl0p я не о частностях. Нужно определение для такого типа решений.

**Comment by Fl0p** [comment]
Любые решения которые влияют на жизнь ХСа и/или затрагивают более одного мембера,
решения которые кому-то могут не понравится.

мембер Алиса поставил йолку по центру ХСа ему так захотелось.
мембер Боб не любит йолки - взял и создал голосовалку о целесообразности йолки в ХС
все остальные которых это хоть как-то волнует - тыкнули кнопу да/нет.
Игого: получилось решение быть или не быть йолке в ХС

🎄

**Comment by Fl0p** [comment]
@abitrolly Может на блокчейне реализуешь :) нафиг нам руби ?

**Comment by k2m30** [comment]
@Fl0p 
> Любые решения которые влияют на жизнь ХСа и/или затрагивают более одного мембера,
решения которые кому-то могут не понравится

Это касается вооще любого изменения. Даже решение подмести пол затрагивает весь ХС и более, чем одного участника :)

**Comment by Fl0p** [comment]
@k2m30 решение подмести пол не может кому-то не понравиться или может?
Если может пусть этот недовольный создает голосовалку - у него для этого есть возможность.

можно добавить туда необратимые/сложнообратимые изменения.

Вообще придумывать идеальную систему - так себе занятие. Нужно внедрить какую-нить альфу и допиливать потом баги.

**Comment by Komzpa** [comment]
На всякий случай: на голосованиях в общественных организациях (наблюдал в OSMF) вопросы формулируются "поддерживаете ли вы это изменение", изменение принимается, если больше 50% от общего числа членов за; воздержавшиеся считаются в общее число (т.е. "воздержался"="нет").

**Comment by Gromina** [comment]
Только давайте не назначать голосование на "сегодня через час голосование заканчивается". Или побольше срок или какой-то кворум надо собирать

**Comment by Fl0p** [comment]
@Komzpa и @Gromina Об одном и том-же.

**Comment by abitrolly** [comment]
https://github.com/loomio/loomio - до блокчейна. Но вообще технологии проблем с людьми не решают. Про камеры опущу, бо оффтопик. Например:

> мембер Боб не любит йолки - взял и создал голосовалку о целесообразности йолки в ХС
> все остальные которых это хоть как-то волнует - тыкнули кнопу да/нет.
> Игого: получилось решение быть или не быть йолке в ХС

Может проблема в Бобе? Кто из мемберов восстанет против Боба? Или зачем вообще эту канитель с ёлкой развели? Если голосовать за то, чтобы **не делать** что-то, то это глупо. Вопрос только в том, как из этого получить фан.

**Comment by abitrolly** [comment]
@Gromina на ren'py можно историческую игру запилить - становление и развал римской империи, т.е. хакерспейса. Все события фиксировать и давать новичкам играть, а ответы складывать, чтобы они мнение тоже учитывалось, а то правил тут понаписывают, родишься и пол-жизни потратишь, чтобы с ними разобраться.

**Comment by Fl0p** [comment]
Может совет директоров или диктатор нам поможет?
https://groups.google.com/forum/#!topic/hackerspace-minsk/W5-Ew-bvWik

**Comment by k2m30** [comment]
stale

**Comment by abitrolly** [comment]
@jekhor @Fl0p stale?
