### ISSUE TITLE
Мелкий шрифт на странице с правилами

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#172]
Вероятно, после #146 шрифт на странице с правилами ХС стал мелким, не таким, как на остальных.

**Comment by Fl0p** [comment]
Ну да разметка стала немного другая теперь markdown
Шрифты теперь все одинаковые (на сколько мелкие парсер отвечает) и заголовки

такие
====

и такие
-------

**Comment by jekhor** [comment]
Ага, это не на странице с правилами шрифт мелкий, это на всех остальных страницах весь текст идёт в классе "lead", и bootstrap задаёт ему размер 21px.

**Comment by abitrolly** [comment]
О, меня вчера Сергей @Sergyenko с кафедры информатики БГУ спрашивал, нет ли задач недельных/двух для студентов по Ruby из реального мира. Вот мне кажется отличный трекер в закладки.

**Comment by k2m30** [comment]
Надо глобальный стиль поменять, твой фикс не сработает

**Comment by jekhor** [comment]
У меня работает. Костыль, конечно, но на том же уровне, что и в остальных местах.

**Comment by k2m30** [comment]
@jekhor Ты уже деплоил?

**Comment by jekhor** [comment]
Нет, локально проверял.
