### ISSUE TITLE
Реализовать самостоятельную регистрацию аккаунтов (с одобрением админом)

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#173]
Чтобы не ловить каждый раз человека, который вручную полезет в Rails и создаст пользователя, нужно задействовать функционал самостоятельной регистрации с последующим одобрением админами (Devise это умеет).

**Comment by jekhor** [comment]
На данный момент пока реализовано создание пользователя админом на сайте, без консольки.

**Comment by k2m30** [comment]
stale
