### ISSUE TITLE
Уведомление участника при получении взноса

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#180]
Надо присылать участнику e-mail при получении от него взноса (через ерип или ручным вбиванием).

**Comment by Komzpa** [comment]
через ерип уже присылается бепейдом, нужно ли второе? :)

**Comment by jekhor** [comment]
Да. Подтверждение о получении, плюс уведомление о сроке действия платежа.

**Comment by k2m30** [comment]
stale

**Comment by jekhor** [comment]
Слишком актуально, чтобы сгинуть заброшенным багом.

**Comment by Fl0p** [comment]
Интернетбанкинг шлет СМС
Бепейд шлет емэйл если указал.
@jekhor  Зачем еще от нас третий раз?

**Comment by jekhor** [comment]
Как подтверждение получения.

**Comment by k2m30** [comment]
три письма об одной транзакиции - вот я бы бесился :)

**Comment by vicseq** [comment]
On May 14, 2018, at 1:39 PM, Mikhail Chuprysnki <notifications@github.com> wrote:
> три письма об одной транзакиции - вот я бы бесился :)
> 
И только последнее — от получателя — имеет смысл. А если ты деньги отправил в ХС, а они пришли в БРСМ?
