### ISSUE TITLE
Add page "Join us"

### ISSUE THREAD

**Issue by vicseq** [minsk-hackerspace/hackerspace.by#182]
Add a page "Join us" accessible from the main menu.

The initial content for the page can be taken from message in the mailing list: https://groups.google.com/d/msg/hackerspace-minsk/ILVMZuGF-lo/-r8oNr2VBgAJ 

Application form: instead of a link to google docs https://docs.google.com/document/d/1tOBfQjZ3FM-ml4sA1pvUTuxsay7tKldXxLQ64SCCw7c/edit?usp=sharing the PDF file hosted at the hackerspace.by site can be used.

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/commit/b4e17fc7c612d391febbb2dc6ff192924a21c637 
done

**Comment by k2m30** [comment]
Жуткая канцелярщина. Надо будет переписать текст для людей.

**Comment by yahor** [comment]
@k2m30 так, трэба каму творчаму дэлегаваць гэтае напісанне :)
