### ISSUE TITLE
Display rent cost - actual and planned

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hackerspace.by#183]
* [ ] get rent contract online
* [ ] expose current rent value through API
* [ ] expose historical rent and planned value through API
* [ ] extract paid rent value from DB
* [ ] create diagram with rent value requirements, deadline and past payments

**Comment by k2m30** [comment]
stale

**Comment by abitrolly** [comment]
Still actual for me.

**Comment by k2m30** [comment]
@abitrolly ну так сделай, раз актуально. уже скоро год висит, актуальнее некуда.
