### ISSUE TITLE
Сайт, новая реальность

### ISSUE THREAD

**Issue by k2m30** [minsk-hackerspace/hackerspace.by#184]
- [ ] Разместить информацию о том, как платить, в легко находимом очевидном месте
- [ ] Разместить информацию о тарифах в легко находимом очевидном месте
- [ ] Правила в легко находимом очевидном месте

**Comment by Fl0p** [comment]
Нужны статичные страницы, много страниц по образу и подобию страницы rules.

Предлагаю сделать так:
В верхнем меню после главной сделать отдельный дропдаун "pages" или "info"
В этом разделе выгребаются все .md или .html с нашего репозитория и рендерятся в соответственном формате.

В этот дропдаун запихнуть страницы:
 contacts /  rules / how_to_join / tariffs / how_to_pay /

Так же нужны ссылки на эти страницы в тексте на главной (поменяю скоро)

**Comment by k2m30** [comment]
Я сделал немного по-другому, плюс я по-прежнему не одобряю идею с гитхабом. Безграмотность, канцелярщина и косноязычие не должны попадать на сайт. Вот жалею теперь, что не сохранил версию c трешем, который был на странице со способами оплаты.
#185
