### ISSUE TITLE
ЕРИП-карма участника

### ISSUE THREAD

**Issue by cardamo** [minsk-hackerspace/hackerspace.by#194]
Чатик играет в карму, а также обсуждает вопрос об оценке контрибуций в ХС (что также осбуждалось в #179)

Предлагаю добавить возможность плюсануть члену в карму через ЕРИП, а также отображать размер кармы на сайте.

Сейчас самым простым способом сделать это мне видится следующие.
Использовать существующий "Благотворительный взнос" в ЕРИП, но присвоить проектам номера непересекающиеся с номерами участников (+10000 например).
Тогда изменения потребуются только со стороны сайта.

**Comment by Fl0p** [comment]
Правильная карма получится.
+1р в карму тебе за идею
+10р в карму тому кто на сайте выведет эту карму

**Comment by cardamo** [comment]
да за 11 рублей я сам хакну эти ваши руби

**Comment by k2m30** [comment]
Сайтом мы почти не пользуемся. 
А фича была бы интересна только студентам имхо, которым +10р это пловина взноса. Бородатых дядек этим не завчелешь, кмк.

**Comment by k2m30** [comment]
м?

**Comment by cardamo** [comment]
как-то не зашла идея, можно закрывать
