### ISSUE TITLE
Более доступная кнопка пожертвований

### ISSUE THREAD

**Issue by xynta** [minsk-hackerspace/hackerspace.by#197]
На одной линии с пунктами меню:
Главная Проекты Контакты Присоединиться Хакерам                                                  Баланс ХС Выход

Вставить пункт "поддержать сообщество" с ссылкой на https://hackerspace.by/payment

Что бы выглядело примерно вот так:
Главная Проекты Контакты Присоединиться Хакерам         Поддержать сообщество Баланс ХС Выход

**Comment by k2m30** [comment]
stale
