### ISSUE TITLE
Баланс падает в ноль и делает выщербину в графике

### ISSUE THREAD

**Issue by Komzpa** [minsk-hackerspace/hackerspace.by#207]
![image](https://user-images.githubusercontent.com/810638/33261460-e23704fc-d373-11e7-9251-b083589dd728.png)

**Comment by abitrolly** [comment]
А где код?

**Comment by jekhor** [comment]
Здесь: https://github.com/minsk-hackerspace/hackerspace.by/blob/master/lib/bepaid.rb
И здесь: https://github.com/minsk-hackerspace/hackerspace.by/blob/master/app/models/balance.rb

Нужно добавить корректную обработку ошибок со стороны банка.

**Comment by jekhor** [comment]
И тут: https://github.com/minsk-hackerspace/hackerspace.by/blob/master/app/models/bank_transaction.rb

**Comment by abitrolly** [comment]
Я так понимаю, без сайта эта хрень не работает и не тестируется? Мы тут открытый API для банков дизайним за еду в свободное время (которого нет) - https://github.com/openapiby - если сделаем норм, то "эксперты", которые по заказу нац.банка сейчас исследование делают (за бабло), потом включат это в официальные рекоммендации.

В общем, нужна отдельная либа с докой, как её запустить и как этот баг тестить - типа какая ошибка и т.п.
