### ISSUE TITLE
User Account update

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#214]
Добавить полей в юзера.

Открытых для изменения пользователю:

- String : telegram_username - строка (можно с парсингом и кликабельным урлом вида https://t.me/Username )
- String : alice_greeting - строка для алиски (как она будет читать)
- String List : mac_list - текстфилд куда юзер может вписать свои макадреса 

Поправить название поля
В профайле `Слоган` на то как он написан в списке `Примечание` 

Добавить редактируемые только админом поля:

- Date : last_seen_date Дата последнего присутствия 
- Boolean : account_suspended (чтобы скрыть акк в списке)
- Boolean : account_banned (чтобы делать блэклисты)

**Comment by Fl0p** [comment]
linked with https://github.com/minsk-hackerspace/hackerspace.by/issues/211

**Comment by Fl0p** [comment]
linked with https://github.com/minsk-hackerspace/hackerspace.by/issues/212

**Comment by yahor** [comment]
магу зрабіць

**Comment by k2m30** [comment]
@yahor хей, уже сделано - #219

**Comment by yahor** [comment]
@k2m30  👍
