### ISSUE TITLE
Социальные кнопки

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#256]
Я как пользователь хочу на сайте видеть кнопочки иконочки с линками на социальные медиа:

* Github - https://github.com/minsk-hackerspace/
* Facebook -  https://www.facebook.com/hs-minsk
* Instagram - https://www.instagram.com/byhackerspace/
* Youtube - https://www.youtube.com/channel/UCoRCmZJBL-zV3-U5e6iB2gQ
* Google+ - https://plus.google.com/communities/110277676123000449866

Наверное это поможет:
https://github.com/FortAwesome/font-awesome-sass

**Comment by Fl0p** [comment]
Можно в шапке как-то так
![images](https://user-images.githubusercontent.com/1046777/37294416-cb22c4a8-2626-11e8-97f6-e5be4d723023.png)

**Comment by AliakseiLeanovich** [comment]
добавил в подвал, в шапке, мне кажется, места мало и смотрится не очень

**Comment by Fl0p** [comment]
А у нас есть подвал? Ну ладно :)

**Comment by AliakseiLeanovich** [comment]
Ну вот появился, если никто не возражает :)
Можно туда же адрес/контактные данные закинуть, ссылки на карту и правила и т.д.
