### ISSUE TITLE
True responsive for mobile

### ISSUE THREAD

**Issue by yahor** [minsk-hackerspace/hackerspace.by#286]
зрабіць каб быў на мабілах рэальна рэспонсів

**Comment by yahor** [comment]
@AliakseiLeanovich зможаш?

**Comment by AliakseiLeanovich** [comment]
@yahor я бы с радостью, но это довольно большой кусок работы, быстро не управлюсь
могу по кусочкам кидать исправления

**Comment by yahor** [comment]
@AliakseiLeanovich  Галоўнае не зламаць. Давай пачнем рабіць гэта ў асобным бранчы?

**Comment by AliakseiLeanovich** [comment]
@yahor да, давай :+1:

**Comment by jekhor** [comment]
Праверыць, ці актуальна

**Comment by yahor** [comment]
@jekhor  на колькі я бачу толькі карцінкі трэба падправіць на старонцы https://hackerspace.by/thanks і на show падзякі.
Падпраўлю і думаю тады закрыем таску.

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/issues/286
