### ISSUE TITLE
Footer positioning

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#289]
#284 и #280 Так и не пофиксили футер как следует.
Теперь он всегда виден внизу экрана, что еще хуже чем было.

- Футер должен быть внизу страницы.
- Если контента на странице меньше чем влезает в экран футер должен быть внизу экрана.

**Comment by abitrolly** [comment]
На статический контент верстальщик бы нашёлся, а тут нужен рубист/хамл/сцсс-верстальщик. Таких профи мало. Либо умеешь сайт собрать, либо футер забахать. :D

**Comment by k2m30** [comment]
@abitrolly bullshit

**Comment by abitrolly** [comment]
The truth is in the eye of beholder.

**Comment by Fl0p** [comment]
@abitrolly 
Гляди https://rubygems.org/gems/bootstrap уже под миллион инсталлов.
Не похоже на то что таких профи мало.

+ Либо разобраться.
