### ISSUE TITLE
Падобна што detected_at_hackerspace не працуе

### ISSUE THREAD

**Issue by yahor** [minsk-hackerspace/hackerspace.by#306]
User.all.map(&:last_seen_in_hackerspace)
 => [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil] 
@jekhor гэта праблема Боба ці Алісы?

**Comment by abitrolly** [comment]
@yahor гэта праблема адсутнасцi докау.

**Comment by k2m30** [comment]
@yahor пока не допилили Алису + для этого нужно внести мак-адреса для каждого пользователя.

**Comment by yahor** [comment]
@k2m30 @jekhor яшчэ актуальна?

**Comment by jekhor** [comment]
Не, гэты функцыянал зараз не выкарыстоўваецца.
