### ISSUE TITLE
Автоматический Suspend

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#312]
Сейчас флаг suspended у юзера выставляется вручную. и это напряжно.

Автоматический suspend работает так:
- Если очередной членский взнос просрочен более чем пол месяца - юзеру автоматически выставляется флаг suspended и мы считаем такого пользователя больше не активным.
(в последствии реализуем отзыв ключа)

- Если у юзера который suspended вдруг приходит платеж флаг suspended автоматически снимается и юзер считается вновь активным.

- Ручное выставление флага админом убрать.
(для ручного управления есть флаг banned)

**Comment by Fl0p** [comment]
👍 thumbsup

**Comment by yahor** [comment]
@Fl0p  work in progress..

**Comment by yahor** [comment]
@Fl0p я так разумею можна правяраць end_date у апошняй аплаты. То бок у Эріп спецыяльна хадзіць не патрабуецца. так?
Проыклад, start_date: "2018-07-26", end_date: "2018-08-25"

**Comment by Fl0p** [comment]
@yahor Так
