### ISSUE TITLE
TODO: Добавить контроль прав доступа в контроллере settings

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#332]
Сейчас проверяется только то, что пользователь залогинен, но не то, является ли он админом.

**Comment by k2m30** [comment]
нет, не в контроллере

https://github.com/minsk-hackerspace/hackerspace.by/blob/master/app/models/ability.rb

**Comment by jekhor** [comment]
Да, но использовать Ability надо в контроллере.
