### ISSUE TITLE
Проверять создаваемые платежи и транзакции на уникальность

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#337]
Иногда bePaid присылает сразу 4 уведомления об одном платеже. Надо обрабатывать только один раз.

![image](https://user-images.githubusercontent.com/117467/44686988-9c3eb780-aa58-11e8-93d3-9f59cccd8434.png)

**Comment by yahor** [comment]
@jekhor Унікальнасць павінна быць па transaction_id ?

**Comment by jekhor** [comment]
@yahor так, альбо па uid, яны аднолькавыя.

**Comment by yahor** [comment]
@jekhor @AliakseiLeanovich Вось так зрабіў
https://github.com/minsk-hackerspace/hackerspace.by/pull/339

**Comment by yahor** [comment]
@jekhor можна закрываць?
