### ISSUE TITLE
Интеграция с Брамником

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#367]
В БД для юзера добавить три поля  "карочка", "код" и "дата действия кода"
- Карточка 8 байт максимум. но бывают карточки 7 и 4 байта.
- Код 8 цифр
- Дата - дата.

В интерфейсе сделать поле для добавления карточки (по типу того как сделан мак адрес)
Юзер должен иметь возможность вбить айди карточки сам. Так же это может сделать админ.

Для генерации кода должна в интерфейсе нужна кнопка. 
Код должен генерится рандомом со сроком действия + 60(?) минут от момента генерации.
Так же эта фича доступна юзеру и админу.

- Проапдейтить апишку hackers.json
отдавать данные поля только при присутствии токена (токен будет на брамнике)
без токена отдавать тот же hackers.json но без этих полей

**Comment by jekhor** [comment]
Типы полей "карточка" и "код"?
Какова семантика поля "код"? Код чего? Временный код доступа?

Как передаётся токен? Где он хранится и как генерируется?

**Comment by jekhor** [comment]
У нас сейчас есть возможность создавать пользователей с ролью "device". Может, использовать какой-нибудь вариант штатной авторизации для брамника? Типа авторизовался, получил кукис, с этими кукисами сходил за hackers.json? Или вообще http basic auth, через https не страшно.

**Comment by Fl0p** [comment]
Если сумеешь то давай сделаем пару пользователей девайс.
У нас уже есть один для Алисы используется.
https://hackerspace.by/hackers/80
И он же тянет этот же hackers.json для приветствий и мак адресов

**Comment by Fl0p** [comment]
Поле код - число 8 цифр
Пока используется вместо карточки - временные коды, когда потерял карточку.
Можно позже сделать однодневные посещения

Поле карточка такое же как и макадрес - байты
Только размер разный 8, 7 или 4 байта (в зависимости от типа карточки)

**Comment by Fl0p** [comment]
@jekhor еще нужно реализовать 
https://github.com/minsk-hackerspace/hackerspace.by/issues/312
Ибо задолбало ручками выставлять суспенд.
Пусть Брамник на этот флаг тоже ориентируется плюс на дату.
Когда период закончился дверь открывает, но моргает грозно что скоро закончится.
А когда автосаспенд, то и не открывает вовсе.

**Comment by Fl0p** [comment]
👍
