### ISSUE TITLE
Ошибка с заголовком X-XSS-Protection

### ISSUE THREAD

**Issue by davojta** [minsk-hackerspace/hackerspace.by#380]
Ошибка в браузерной консоли

Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 13. The default protections will be applied.

![image](https://user-images.githubusercontent.com/893650/54923897-419d0980-4f1c-11e9-84ac-4e82a0d176b8.png)

**Comment by jekhor** [comment]
В каком случае?

пн, 25 сак 2019, 16.37 карыстальнік Dzianis Sheka <notifications@github.com>
напісаў:

**Comment by jekhor** [comment]
@che наверное, по твоей части.

**Comment by davojta** [comment]
просто при открытии сайта.

**Comment by jekhor** [comment]
Это из-за того, что заголовок почему-то встречается два раза. @che 

![image](https://user-images.githubusercontent.com/117467/55029787-008c1e80-501c-11e9-89fe-a85745b8e6fa.png)

**Comment by yahor** [comment]
А не можа быць так што адзін раз аддае Rails, a яшчэ раз дакідвае загаловак Nginx ?

**Comment by jekhor** [comment]
Не проявляется.
