### ISSUE TITLE
Добавить информацию на главную страницу

### ISSUE THREAD

**Issue by zlidzen** [minsk-hackerspace/hackerspace.by#405]
Добавить информацию о расположении MalinoHS в раздел "Как нас найти? Приходите."

**Comment by abitrolly** [comment]
Куда добавить. Для начала поиск по гитхабу - https://github.com/minsk-hackerspace/hackerspace.by/search?q=%D0%BA%D0%B0%D0%BA+%D0%BD%D0%B0%D1%81+%D0%BD%D0%B0%D0%B9%D1%82%D0%B8&unscoped_q=%D0%BA%D0%B0%D0%BA+%D0%BD%D0%B0%D1%81+%D0%BD%D0%B0%D0%B9%D1%82%D0%B8

Судя по всему на сайте есть какая-то многоязычность. Строка для MalinoHS есть, но не отображется на глагне.

https://github.com/minsk-hackerspace/hackerspace.by/blob/b942a1b837dcbdb7092f71392750b3b4bab36047/config/locales/ru.yml#L49-L58

Зато другие отображаются.

https://github.com/minsk-hackerspace/hackerspace.by/search?q=how_to_find_content_text&unscoped_q=how_to_find_content_text

Впилить можно здесь.

https://github.com/minsk-hackerspace/hackerspace.by/blob/f03207b1c977048fedd8befb85ecc06773776279/app/views/main/index.html.haml#L85-L86
