### ISSUE TITLE
Разные шрифты при открытии в MacOS и Linux

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#426]
Задумано было так, как в MacOS.

Linux:

![image](https://user-images.githubusercontent.com/117467/75592189-b664b600-5a92-11ea-98c9-ceb848b7c398.png)

MacOS:

![image](https://user-images.githubusercontent.com/117467/75592237-d7c5a200-5a92-11ea-948b-fe1620dbb1c8.png)

**Comment by k2m30** [comment]
application.css.scss:

```css
font-family: 'Helvetica Neue', 'Open Sans', sans-serif;
```

Поведение штатное, так задумано, всё по w3s:

`The font-family property can hold several font names as a "fallback" system. If the browser does not support the first font, it tries the next font.`
