### ISSUE TITLE
При деплое заново устанавливаются гемы в bundler

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#450]
Когда смотришь логи travis, видно, что bundle install отрабатывает долго, все гемы ставятся заново, как будто не пошарена директория vendor/bundle. Но она пошарена. Надо разобраться, чтобы процесс деплоя был быстрее.

**Comment by abitrolly** [comment]
0.39 ceкунды же на инсталл. Где ты смотришь?

https://travis-ci.org/github/minsk-hackerspace/hackerspace.by/jobs/686008666#L221

**Comment by jekhor** [comment]
1311 стррка и далее

Я в живом эфире наблюдал глазами, долго длится.

нд, 17 мая 2020, 14.14 карыстальнік Anatoli Babenia <
notifications@github.com> напісаў:

**Comment by abitrolly** [comment]
@jekhor так это ж не на трависе. Эта `mina` ж через SSH на сервере всё делает. И она создаёт новую директорию, на которую потом переключает. Так что туда надо смотреть. Travis тут не при чём.

**Comment by jekhor** [comment]
А где в исходном тексте тикета про травис?

нд, 17 мая 2020, 17.15 карыстальнік Anatoli Babenia <
notifications@github.com> напісаў:

**Comment by jekhor** [comment]
А, понял, о чём ты. В трависе это просто видно, а при запуске руками, емнип, не видно было.

**Comment by abitrolly** [comment]
Ну что, теперь 51 секунда на деплой https://travis-ci.org/github/minsk-hackerspace/hackerspace.by/builds/721471306#L823 против 239 https://travis-ci.org/github/minsk-hackerspace/hackerspace.by/builds/715458764#L842

Я пока не вижу где можно ускорить. Только если какой-то профайлинг добавлять. Закрываем?
