### ISSUE TITLE
Сортировка рекомендателей по # участника

### ISSUE THREAD

**Issue by Fl0p** [minsk-hackerspace/hackerspace.by#453]
![Screen Shot 2020-05-14 at 12 32 03](https://user-images.githubusercontent.com/1046777/81918353-04dc1800-95df-11ea-8036-84cf948e773c.png)
Сейчас невозможно что-то найти

**Comment by yahor** [comment]
Зроблена! https://github.com/minsk-hackerspace/hackerspace.by/pull/547
