### ISSUE TITLE
Сделать ротацию логов

### ISSUE THREAD

**Issue by tequilarusa** [minsk-hackerspace/hackerspace.by#464]
Убрать debug режим и везде сделать production

**Comment by abitrolly** [comment]
@tequilarusa а какую проблему это решает?

**Comment by k2m30** [comment]
там везде production

**Comment by jekhor** [comment]
> Убрать debug режим и везде сделать production

да, там везде production

**Comment by jekhor** [comment]
> @tequilarusa а какую проблему это решает?

у нас логи не ротируются, за полгода набегает полтора гигабайта.

**Comment by k2m30** [comment]
This is what you need in your config/environments/production.rb

Keeps the Last 5 log files which are rotated at every 10MB

`config.logger = Logger.new(config.paths[“log”].first, 5, 10.megabytes)`

@jekhor оно?

**Comment by jekhor** [comment]
Похоже. Там вроде Паша что-то системными средствами сделал

пн, 1 лют 2021, 13.56 карыстальнік Mikhail Chuprysnki <
notifications@github.com> напісаў:

**Comment by k2m30** [comment]
done
