### ISSUE TITLE
Projects are non-translatable

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/hackerspace.by#470]
https://translate.google.com/translate?hl=&sl=ru&tl=en&u=https%3A%2F%2Fhackerspace.by%2Fprojects%2F42

![image](https://user-images.githubusercontent.com/8781107/99567182-ea945400-29de-11eb-9b01-d1c05b0e411f.png)

**Comment by shrddr** [comment]
надо заголовок accept: text/html послать и тогда отдаст хтмл

**Comment by abitrolly** [comment]
Так почему он его по дефолту не посылает?

**Comment by abitrolly** [comment]
Yep. It works right now. @jekhor thanks. )

**Comment by abitrolly** [comment]
This what Google Translate sends.

connection | close
-- | --
accept-encoding | gzip,deflate,br
user-agent | Mozilla/5.0 (X11;  Fedora; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0,gzip(gfe)
accept | */*
host | webhook.site
via | 1.0 translate.google.com TWSFE / 9.0
content-length |  
content-type |
