### ISSUE TITLE
1. Добавить календарь на сайт

### ISSUE THREAD

**Issue by tequilarusa** [minsk-hackerspace/hackerspace.by#482]
Добавитьgoogle календарь или вставить html код, предлагаемый Google

**Comment by abitrolly** [comment]
Есть какая-то такая вот штука https://github.com/discourse/discourse-calendar

**Comment by k2m30** [comment]
Уже было, можно просто откатить

https://github.com/minsk-hackerspace/hackerspace.by/issues/94

**Comment by abitrolly** [comment]
https://github.com/fedora-infra/fedocal тоже есть, но это отдельная аппа, которая требует MP - maintenance points на разворачивание и поддержку. Не уверен, что ХС генерирует сейчас достаточно питоновской маны для такого.

**Comment by jekhor** [comment]
Имеющийся календарь хакерспейса пустой. Видимо, существуют какие-то другие?
<iframe src="https://calendar.google.com/calendar/embed?src=ti66tjoohvkqc5j2c603te0m9g%40group.calendar.google.com&ctz=Europe%2FMinsk" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by yahor** [comment]
Актуальна? А трэба? Каляндаром народ карыстаецца?

**Comment by abitrolly** [comment]
Пока не затерроризировали всех, и что-то происходило, это был способ увидеть, что творится в ХСе, и придти когда интересно.

**Comment by yahor** [comment]
Думаю фіча пакуль не актуальна і можна закрываць.

**Comment by abitrolly** [comment]
Сейчас неактуально, но календарь нужен. Хотя бы для дня открытых дверей.

**Comment by yahor** [comment]
@abitrolly ну ў нас жа і так вісіць на галоўнай "Каждый четверг в [Зелёном](https://hackerspace.by/contacts#green) , а каждый вторник в [Малиновом](https://hackerspace.by/contacts#malino) хакерспейсах у нас вечер открытых дверей. Начало в 19:00. Окончание — после 22:00."

**Comment by abitrolly** [comment]
Висит, да, но я два раза пытался попасть и пришлось звонить Жене. Без меня два раза люди вообще не попали. Поэтому лучше было бы не формальный день, а открывать его. Добавляя запись и инструкции, или контакт, кому писать, чтобы найти или дверь открыть.
