### ISSUE TITLE
Заглавное фото при загрузке новости

### ISSUE THREAD

**Issue by tequilarusa** [minsk-hackerspace/hackerspace.by#486]
При создании новости предлагается загрузить фотографию. Ее размер 200х200, и она используется на странице новостей:
https://hackerspace.by/news
Если затем щелкнуть на конкретную новость, то загружается и краткое описание новости, и вот эта маленькая фотография, и остальное все.
Возможно убрать загрузку этого заглавного изображения 200х200 и краткого описания, а оставить только то, что написано в блоке "Основной текст"?

**Comment by jekhor** [comment]
Мне кажется, что это не очень хорошая идея... Надо что-то придумать тогда с вёрсткой. Картинку можно показывать и побольше, если что.

С картинкой:
![image](https://user-images.githubusercontent.com/117467/108638753-d2324a80-74a1-11eb-9f15-add640fa8b06.png)

Без картинки:
![image](https://user-images.githubusercontent.com/117467/108638811-22a9a800-74a2-11eb-9531-9f1a949f3441.png)

**Comment by yahor** [comment]
Думаю проста трэба прыбраць з старонкі навіны кароткае апісанне і дадаць абцяканне тэкстам карцінкі.
@jekhor @tequilarusa a?

**Comment by jekhor** [comment]
Ну можа і так...

**Comment by yahor** [comment]
@jekhor @tequilarusa ну давайце зробім так.

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/pull/556
