### ISSUE TITLE
Шапка наползает на контент (везде) и не переключается на мобильную версию на телефоне

### ISSUE THREAD

**Issue by Arcturuss** [minsk-hackerspace/hackerspace.by#492]
Шапка сайта нормально работает только на полной ширине. 
Если уменьшать ширину - шапка увеличивается в высоту и закрывает контент.

При ширине меньше 768 px шапка переключается в "мобильный режим" с одной иконкой, но 768 - это очень мало. На современных мобилах этого не хватает, и шапка отображается в десктопном варианте.

десктоп
![image](https://user-images.githubusercontent.com/465493/109360788-e2c73400-7898-11eb-8066-78ffe4f9bd4c.png)

мобила
![image](https://user-images.githubusercontent.com/465493/109360890-05594d00-7899-11eb-9078-2e30e3a55a46.png)

**Comment by vasja-slvm** [comment]
Шапка сайта не работает нормально на полной ширине на экране если это 1200.  
![Картинка](https://user-images.githubusercontent.com/19436101/109361219-9fb99080-7899-11eb-83dd-6b1363e10446.jpg)
Алсо, у меня упорно никак не отображает слопывание шапки даже на меньшей ширине :( 
![320px](https://user-images.githubusercontent.com/19436101/109361481-09d23580-789a-11eb-9c9c-ac4a466941dd.jpg)

**Comment by Arcturuss** [comment]
вижу две с половиной проблемы: 
- текста в шапке дофига
- слишком поздно переключается на мобильную версию
- маловат отступ для контента сверху, даже в лучшем случае логотип наползает на первый заголовок

отступ фиксится просто: `body { margin-top: 80px; }` 
80 px достаточно, чтобы логотип не наползал на текст

переключение на мобильную версию лучше поменять в scss - переопределить переменную бутстрапа. а то там слишком дофига стилей, замучаешься их по одному переопределять. типа так:

    $screen-sm: 1090px;
    $screen-sm-min: $screen-sm;
    $screen-tablet: $screen-sm-min;
    
    @import 'bootstrap';

на работоспособность не проверял. ширину в 1090 определил экспериментальным путем с учетом фиксов ниже. для мобил может быть недостаточно.

слегка причесать шапку.
html блока с балансом. заворачиваем текст в span, чтобы можно было его скрывать и оставлять только шкалу:

    <li>
    <a href="/chart">
    <span class="navbar-collapsible">
    Баланс: <b>3558.96</b>
    </span>
    <meter high="75" low="25" max="100" min="0" optimum="100" value="21.0">
    (21.0%)
    </meter>
    </a>
    </li>

css

    @media (max-width: 1290px) {

    /* убрать подпись у баланса */
    .navbar-collapsible {
        display: none
    }
    
    /* уменьшить логотип */
    .navbar-brand {
        padding: 8px 15px;
        line-height: 10px;
    }
    .navbar-brand img {
        width: 50px;
        height: 38px;
        object-fit: contain;
    }
    }

![image](https://user-images.githubusercontent.com/465493/109361706-87964100-789a-11eb-909d-6788191e3d2f.png)
    
![image](https://user-images.githubusercontent.com/465493/109361689-7f3e0600-789a-11eb-8038-f26bc6295292.png)

**Comment by abitrolly** [comment]
Боюсь что все дизайнеры "в отпуске", но если будет PR, то я не вижу причин чтобы его задерживать.
