### ISSUE TITLE
Подвал наползает на содержимое сайта в мобильной версии

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#500]
На телефоне подвал разрастается и закрывает кнопки/текст.
Related to: #492 

![image](https://user-images.githubusercontent.com/117467/116389536-b8a4da80-a825-11eb-8282-935b5fe83511.png)

**Comment by abitrolly** [comment]
@Arcturuss можешь глянуть что тут надо поправить?

**Comment by Arcturuss** [comment]
Да, поправил. Заодно пофиксил масштабирование мобильной версии и еще всякое
