### ISSUE TITLE
Прописать правильные метатеги для соцсетей

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#503]
Для того, чтобы предпросмотр в соцсетях был красивым — прописать правильно opengraph метатеги.

**Comment by abitrolly** [comment]
А картинки с превьюхами не надо для них? Вряд ли пауки их сами рендерят.

**Comment by yahor** [comment]
@jekhor @abitrolly  адкуль браць апісанні старонак? 
title - ?
description - ?

На колькі я бачую, старая праблема з кантэнтам засталася.
Можа быць проста рукамі напісаць апісанне і назву пад кожны раздзел, пасля аўтаматычна падстаўляць тэкст?

**Comment by abitrolly** [comment]
Чтобы понять о чём речь, было бы неплохо список всех страниц для начала, и скрин, как рендерятся дефолтные метаданные, когда нет своих.

**Comment by yahor** [comment]
Пакуль рэндарыцца усё мінімальна і харкодна.

https://github.com/minsk-hackerspace/hackerspace.by/blob/master/app/views/layouts/_og_meta_tags.html.haml
```
%meta{property: "og:title", content: page_title }
%meta{property: "og:type", content: "website" }
%meta{property: "og:url", content: "https://hackerspace.by/" }
%meta{property: "og:site_name", content: "hackerspace.by" }
%meta{property: "og:description", content: page_description }
%meta{property: "og:image", content: image_url('/images/og.png') }
%meta{property: "og:image:secure_url", content: image_url('/images/og.png') }
%meta{property: "og:image:type", content: "image/png"}
%meta{property: "og:image:height", content: "600" }
%meta{property: "og:image:width", content: "600" }
%meta{property: "og:ttl", content: "345600" }
```

https://github.com/minsk-hackerspace/hackerspace.by/blob/master/app/helpers/application_helper.rb

```
  #TODO
  def page_title
    @project.try(:name) || @news.try(:title) || t('site_title')
  end

  #TODO
  def page_description
    strip_tags(t('index.what_is_it_content'))
  end
  ```
Для праекта ці навіны мы зможаш узяць нейкае апісанне з базы. а вось для статычных старонак трэба будзе рукамі прапісаць тэксты якія падстаўляць.

<img width="633" alt="Screenshot 2022-04-28 at 14 42 51" src="https://user-images.githubusercontent.com/222588/165744758-a5df7ff0-35f7-4746-ace8-291c0d4e6895.png">

**Comment by yahor** [comment]
@abitrolly я меў на увазе тэрмін рэндара паршала ў шаблоне рэйлс. 
app/views/layouts/_og_meta_tags.html.haml

**Comment by jekhor** [comment]
@abitrolly Например. А так идёшь в https://developers.facebook.com/tools/debug/ и вбиваешь те URL, которые тебе нравятся.
![image](https://user-images.githubusercontent.com/117467/165841555-e04a6722-bdfe-45ed-bd98-840e99cba339.png)

**Comment by abitrolly** [comment]
> А так идёшь в https://developers.facebook.com/tools/debug/ и вбиваешь те URL, которые тебе нравятся.

![image](https://user-images.githubusercontent.com/8781107/165885825-26782f25-32b2-4cec-869c-656ec9aff5d1.png)

Не нравится мне это. И рендер ниочём.

**Comment by jekhor** [comment]
@abitrolly для того, чтобы отлаживать рендер превьюшки в соцсетях, надо ими пользоваться, да. Увы.

**Comment by yahor** [comment]
У прынцыпе зразумела, што можна зрабіць і палепшыць.
 Пачну працу.

**Comment by yahor** [comment]
@jekhor @abitrolly Ужо выглядае значна лепш.
<img width="746" alt="Screenshot 2022-05-08 at 01 19 09" src="https://user-images.githubusercontent.com/222588/167273592-2a7701b6-0818-47cf-ba44-0ead42a45b9c.png">
<img width="759" alt="Screenshot 2022-05-08 at 01 18 39" src="https://user-images.githubusercontent.com/222588/167273594-2669320f-6ad8-49e6-bd78-c0c80712d796.png">
<img width="794" alt="Screenshot 2022-05-08 at 01 22 14" src="https://user-images.githubusercontent.com/222588/167273657-8f025f31-34fa-41ba-822b-32f3193e7935.png">
<img width="796" alt="Screenshot 2022-05-08 at 01 21 37" src="https://user-images.githubusercontent.com/222588/167273665-0e4a24a3-8da2-411d-a195-42413ace2441.png">

Ня вырашаныя рэчы:

1. Unsupported Image File Extension.
 Provided og:image URL, https://hackerspace.by/images/logo_site.svg does not have a supported extension.

**Comment by abitrolly** [comment]
Крутяк! Вытянуть бы sitemap всех страниц с рендерами для ревью.

Есть какой-то способ сделать сервис в рубях, чтобы он генерил картинки для соц.сетей сразу с встроенным логотипом? Там вообще какие требования к картинкам - надо их масштабировать, или твитторы сами это делают?

**Comment by yahor** [comment]
1. Sitemap неабходна пісаць ручкамі. Днамічна збіраць усё у xml
2. Так, можна зрабіць watermark для карцінак якія запампаваныя ў нашую сістэму. Але калі ставіць лога, то не ведаю як будзе з рэсайзам глядзецца ў сацсетках.
3. Сацсеткі самі маштабуюць. я зрабіў каб аддавалася ад нас 600х600.

PS
Думаю гэтую issue можна закрываць
