### ISSUE TITLE
Новости: показывать дату создания

### ISSUE THREAD

**Issue by vitaly-zdanevich** [minsk-hackerspace/hackerspace.by#528]
А то неясно какого вообще года новость:

![image](https://user-images.githubusercontent.com/3514015/146696066-bb3f2888-d34c-469d-8da4-6d92278cfa29.png)

**Comment by abitrolly** [comment]
Зато создаёт впечатление что есть движ. :D

**Comment by vitaly-zdanevich** [comment]
кхххх)

Ну, новость в год это нормально, анонсы мероприятий можно размещать, мелкие новости, что станок новый появился например, стену покрасили.

**Comment by abitrolly** [comment]
Ну вот никого не осталось, чтобы новость написать.

**Comment by vitaly-zdanevich** [comment]
А ты?

**Comment by abitrolly** [comment]
Я хочу #303 чтобы новости в гите трекать. Но я забил на рельсы - ладно бы, если это был просто руби, но это уже не руби, и слишком много в голову на загрузить, чтобы с ними работать.
