### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by vitaly-zdanevich** [minsk-hackerspace/hackerspace.by#531]

**Comment by abitrolly** [comment]
Я думаю это невозможно. Тебе придётся её выбрать, опросить всех кто код коммитил что они не против. Зачем она тебе? )

**Comment by k2m30** [comment]
когда коту делать нечего.. #116

**Comment by vitaly-zdanevich** [comment]
> Зачем она тебе?

Я хотел логотип загрузить на Commons.

**Comment by jekhor** [comment]
А логотип от сайта отдельно, где-то даже репа была.

аў, 28 сне 2021, 22:15 карыстальнік Vitaly Zdanevich <
***@***.***> напісаў:

**Comment by vitaly-zdanevich** [comment]
https://github.com/minsk-hackerspace/logo

Взял оттуда Зеленый и загрузил на https://www.wikidata.org/wiki/Q110293084
Малинового там нету.

**Comment by abitrolly** [comment]
@tequilarusa а кто лого рисовал для малинового?

**Comment by tequilarusa** [comment]
Я
Я закину в svg

**Comment by tequilarusa** [comment]
Или не я ...
Но у меня есть

**Comment by abitrolly** [comment]
Закидывай. Дьюдил не пройдёт, но как минимум не потеряется. :D
