### ISSUE TITLE
Взносы: перейти от "две недели в долг до суспенда" к "взнос кончился — доступа нет"

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#537]
Сейчас логика такая:

1. после того, как взнос закончился, участник может две недели ходить "в долг", доступ не закрывается
2. если до истечения двух недель был внесён взнос — он начинает действовать от момента окончания предыдущего
3. если две недели истекли — доступ закрывается, долг "обнуляется"
4. закинул взнос хотя бы на один день — доступ открывается, и снова возможны две недели "в долг"
5. напоминания об уплате начинают приходить участнику после истечения взноса

Так было сделано для того, чтобы не закрывать доступ добросовестному участнику, который оплачивает взнос после нескольких напоминаний. Но это создаёт возможность намеренных или ненамеренных злоупотреблений, когда в течение этих двух недель ходят "в долг", но новый взнос уплачивают только после саспенда, что обнуляет долг.

Чтобы сделать логику прозрачной и убрать возможность злоупотреблений, предлагается сделать:

1. Отключать доступ (отправлять в "саспенд") сразу по истечении взноса
2. Включать доступ обратно при уплате взноса не менее, чем на две недели (**месяц? обсудить**) — во избежание ситуаций "хочу прийти — плачу за один день".
3. Начинать напоминать об истечении взноса за неделю (**две?**) до.

**Comment by jekhor** [comment]
Victor:
2. оплата на две недели
3. за неделю

**Comment by vasja-slvm** [comment]
1. Отключать доступ сразу - в целом одобряю, потому что кажется некоторые платят только когда им не открылась дверь. Можно быть добрым и дать ещё один-два дополнительных дня, ну мало ли что. Но не больше трёх.

2. У меня было другое предложение по этому поводу. Если у человека закончился взнос, а потом он через короткое время (меньше месяца) снова пришёл, то считать его взнос не от даты нового платежа, а от даты истечения предыдущего. Потому что вроде как если ты участник, то ты платишь взносы постоянно и без "каникул". При предложенном тобой варианте всё ещё могут быть ситуации, где человек ходит две недели, потом две недели не ходит, потом опять две недели ходит. Это, конечно, может и лучше, чем "не ходит вообще", но звучит сомнительно.
Или вообще всегда при оплате после пропуска, списывать денег за две предыдущие недели (или от конца предыдущего платежа, если это меньше двух недель).
Но если оставлять твой вариант без изменений - то неделя-две. Если у человека два дня назад не было, чем оплатить два дня, то не факт, что ему будет чем оплатить целый месяц. 

3. Напоминать об истечении за неделю - на почту, и дня за три -  в чате. (За две куда угодно - рано). Причём в чяте изменить напоминание, не "уйдут в саспенд", а четко понятно в духе "заканчивается взнос и скоро закроется доступ в ХС у участников:" 

мау
