### ISSUE TITLE
Разрешить пользователю самостоятельно менять тариф

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#539]
Сабж, чтобы не дёргать админов.

При этом:
- разрешить менять не чаще раза в месяц
- присылать уведомление о смене тарифа в чат участников ХС

**Comment by abitrolly** [comment]
* дать возможноть при оплате сообщать на что баблос

**Comment by jekhor** [comment]
@abitrolly членские взносы у нас нецелевые, а сообщать, на что баблос, можно при пожертвованиях. Правда, учёта трат у нас нету толком.

**Comment by abitrolly** [comment]
https://docs.opencollective.com/help/collectives/projects для учёта трат и всего такого.

**Comment by yahor** [comment]
Якія у выніку павінны быць канчатковы патрабаванні да праўкі юзерам свайго тіарыфу?

**Comment by jekhor** [comment]
Пакуль што проста магчымасць самому змяніць тарыф, але не часцей за адзін раз на месяц. Дадатковых умоваў няма. Хаця... У нас там ёсць вельмі хітрыя "службовыя" тарыфы кшталту 0 р/мес., дык іх, напэўна, юзэру лепш не даваць магчымасці выбраць. Гл. https://hackerspace.by/admin/tariffs (не памятаю, ці ёсць адмінскія правы ў цябе). То бок, яшчэ ў мадэлі тарыфа патрэбная пазнака "дасяжны юзэру".

**Comment by yahor** [comment]
Трэба будзе увесці пару новых калонак.

Table :users
- tariff_changed_at: datetime
Table :tariffs
- accessible to user: boolean
  default `false`

**Comment by yahor** [comment]
Зроблена!
https://github.com/minsk-hackerspace/hackerspace.by/pull/546
