### ISSUE TITLE
Ruby version указаць да мінорнай версіі

### ISSUE THREAD

**Issue by yahor** [minsk-hackerspace/hackerspace.by#543]
1. Зараз мы маем ў .ruby-version:
`ruby-3.0`
варта дадаць поўную версію `ruby-3.0.4` каб не было розных версій ў розных энвайраментах.
2. Таксама памяняць ў `.travis.yml`
3. І ў `config/deploy.rb:73`

**Comment by jekhor** [comment]
Ага, у мяне як раз незакамічаная 3.0.2 боўтаецца лакальна, бо з 3.0 не
працаваў rbenv. Толькі тады трэба і на хостынге ўсталёўваць такую ж.

сб, 23 кра 2022, 16:23 карыстальнік Yahor ***@***.***>
напісаў:

**Comment by jekhor** [comment]
Гл. яшчэ #431

**Comment by yahor** [comment]
ага, #431 бачыў, безумоўна трэба адначасова і з версіямі на хостынгу і ў СІ разабрацца.

**Comment by jekhor** [comment]
І паглядзі, там Толік заводзіў баг пра версію рубі таксама

сб, 23 кра 2022, 16:23 карыстальнік Yahor ***@***.***>
напісаў:

**Comment by abitrolly** [comment]
Я не сильно догоняю как RVM работает, но мне кажется можно пропатчить все файлы, чтобы юзался только он для всего.

**Comment by abitrolly** [comment]
Ну или `asdf`, чтобы не дебажить потом конструкции типа "мейк вызывает руби, который вызывает рвм который вызывает другой руби".
