### ISSUE TITLE
падключыць https://codecov.io

### ISSUE THREAD

**Issue by yahor** [minsk-hackerspace/hackerspace.by#558]
Каб бачыць % пакрыцця кода тэстамі ў README як зараз паказваецца білд статус

**Comment by yahor** [comment]
@jekhor % пакрыцця лэйбачка і інтэграцыя з гітхаб праектам https://about.codecov.io/product/feature/badges/

**Comment by jekhor** [comment]
А ёсць жаданне неяк павялічваць пакрыццё тэстамі? Бо калі ніхто на гэтую лэйбачку не глядзіць, то і сэнсу ў ёй нуль.

**Comment by jekhor** [comment]
Не падобна, каб яно працавала...

![image](https://user-images.githubusercontent.com/117467/168421346-d0e3101e-c41e-425c-a9be-67d9a2f60bc3.png)

**Comment by jekhor** [comment]
Я залагініўся, клікнуў на рэпазіторый, яно мне кажа, што трэба зааплоадзіць там нейкія рэзультаты тэста на пакрыццё.

**Comment by yahor** [comment]
@jekhor https://docs.codecov.com/docs/step-2-getting-a-codecov-account-and-uploading-coverage

**Comment by yahor** [comment]
@jekhor яшчэ магчыма трэба будзе спецыяльны json репорт генерыць для адпраўкі/распазнання яго codecov.io

**Comment by abitrolly** [comment]
@yahor запуш просто на GitHub Pages - https://gist.github.com/willprice/e07efd73fb7f13f917ea - а то из-за каких-нибудь санкций сломают репу и всю историю удалят.

**Comment by jekhor** [comment]
Нешта яно касячна пакрыццё генеруе... Нібыта пакрыццё толькі саміх тэстаў.
![image](https://user-images.githubusercontent.com/117467/168486698-c575a76a-4a5e-488c-ac31-9341942946ce.png)

**Comment by jekhor** [comment]
Яно для іх ўласных праектаў паказвае такую ж фігню...

https://app.codecov.io/gh/codecov/Ruby-Standard-1

**Comment by jekhor** [comment]
Ну, прасралася нарэшце...
https://app.codecov.io/gh/minsk-hackerspace/hackerspace.by
