### ISSUE TITLE
Разрешить пользователям добавлять несколько SSH ключей

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#568]
Чтобы иметь возможность доступа с нескольких устройств, пользователь может захотеть добавить более одного SSH ключа. Сейчас у нас допускается только один ключ.
Можно или сделать аналогично NFC ключам (отдельная модель и отношение), а можно просто дать возможность вбить в поле ввода несколько ключей на разных строках (но это усложнит валидацию).

**Comment by yahor** [comment]
@jekhor я думаю поле ssh_public_key можна беззваротна выдаляць ў табліцы users(пасля міграцыі дадзеных)?

**Comment by jekhor** [comment]
Так

нд, 22 мая 2022, 16:38 карыстальнік Yahor ***@***.***>
напісаў:

**Comment by yahor** [comment]
PR https://github.com/minsk-hackerspace/hackerspace.by/pull/571
