### ISSUE TITLE
Дадаць RSS

### ISSUE THREAD

**Issue by vicseq** [minsk-hackerspace/hackerspace.by#59]
Дадаць RSS усіх зменаў на сайце.

**Comment by yahor** [comment]
@vicseq  кожны апдэйт пісаць у рсс ліст ?
у якім фармаце? усіх зменаў кантэнта ці тэхнічных таксама?

**Comment by vicseq** [comment]
Спачатку кожны, потым, калі іх будзе зашмат — падумаем, як фільтраваць. У plaintext, каб любымі чыталкамі можна было б прачытаць, з кантэнтам у самім RSS паведамленні, каб адразу ў чыталцы было бачна, што адбылося, і без перахода па спасылцы ў браўзэры.

**Comment by k2m30** [comment]
@yahor wontfix?

**Comment by yahor** [comment]
@k2m30 ну пакуль рукі не дайшлі прыкруціць гэта
paper_trail павінен зраіць гэта адносна простым. трэба заняцца на тыдні, бо з гугл апі пакуль з валідацыямі не цікава калупацца, не запусукаецца як след :)

**Comment by yahor** [comment]
@k2m30 у працэссе напісання старонкі feed ...

**Comment by k2m30** [comment]
@yahor я не разумею, што i галоўнае, каму, мы будзем выдаваць

**Comment by k2m30** [comment]
И на странице контактов у нас шесть способов с нами связаться плюс три телефона.

Кому там чего не хватает?

**Comment by yahor** [comment]
@vicseq  @k2m30 на колькі я разумею важны апдэйты праектаў і навіны. астатняе не вельмі важна

А з іншага боку хто зараз чыта рсс?

**Comment by Fl0p** [comment]
Сделайте тест.
Повесьте ссылку RSS, а за ней капчу со счетчиком и посмотрите сколько человек на нее кликнет.

**Comment by k2m30** [comment]
Я таму і нават і не браўся, бо не ведаю, каму гэта патрэбна. Да таго ж, мы не публікуем навіны кожны тыдзень, праекты таксама.
 
А калі ёсць нешта важнае, то мы рассылаем емайлы ўсім у google рассылцы і групах FB і VK.
Нешта я сумняваюсь у эфектыўнасці RSS.
