### ISSUE TITLE
Сделать нормальное создание пользователя

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#606]
- [x] - пароль должен генерироваться автоматически
- [x] - пользователю должен высылаться email с паролем и номером участника
- [x] - тариф по умолчанию должен быть "Основной", чтобы не путаться

**Comment by yahor** [comment]
@jekhor я пачаў працаваць тут https://github.com/minsk-hackerspace/hackerspace.by/pull/607

**Comment by jekhor** [comment]
Выдатна, пагляджу ўжо пасля 27 снежня

пт, 22 сне 2023, 10:27 карыстальнік Yahor ***@***.***>
напісаў:
