### ISSUE TITLE
Новому пользователю пришёл пустой пароль в письме

### ISSUE THREAD

**Issue by jekhor** [minsk-hackerspace/hackerspace.by#619]
Заводил нового юзера, с телефона. Пароль в формочке был. Пользователю пришло такое:
![image](https://github.com/minsk-hackerspace/hackerspace.by/assets/117467/7571aef4-8c0c-4578-9296-804cd17fba40)

**Comment by jekhor** [comment]
Не, пустога не было дакладна. І яшчэ адзін мембер пацвердзіў, тое ж самае было, але тым разам я з кампа заводзіў.

**Comment by yahor** [comment]
https://github.com/minsk-hackerspace/hackerspace.by/pull/625/
